#!/bin/bash

awk '
/Copyright .* Open Networking Foundation./ {
    skippingHeader = 1;

    prefix = $0;
    gsub("Copyright .*", "", prefix);
    year = $0;
    gsub(".*Copyright ", "", year);
    gsub(" .*", "", year);
    gsub("-present", "", year);

    print prefix "SPDX-FileCopyrightText: " year "-present Open Networking Foundation <info@opennetworking.org>";
    print prefix
    print prefix "SPDX-License-Identifier: Apache-2.0";
}

{
    if (!skippingHeader) {
        print $0;
    }
}

/limitations under the License./ {
    skippingHeader = 0;
}

' $1