#!/usr/bin/env bash

# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu -o pipefail

modified_charts=$(git show HEAD | grep Chart.yaml | grep +++ | cut -d " " -f2 | sed s^b/^^) || true

modified_component_charts=""
for chart in ${modified_charts}; do
    git diff HEAD^ HEAD ${chart}
    version=$(git diff HEAD^ HEAD ${chart} | grep +version: | cut -d " " -f2) || true
    if [ ! -z ${version} ]; then
        # figure out the tag for this chart
        component=`echo ${chart} | cut -d "/" -f1`
        modified_component_charts="${modified_component_charts} ${component}"
    fi
done

if [ "${modified_component_charts}" = "" ]; then
    echo No charts were modified
    exit 0
fi

count=$(wc -w <<<${modified_component_charts})
count=${count//[[:blank:]]/}
if (( ${count} != 1 )); then
    echo Found more than one modified chart: ${modified_component_charts}
    exit 1
fi

exit 0

