#!/usr/bin/env bash

# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# release-merge-commit
# publishes artifacts for merge commits that bump the version

set -eu -o pipefail

project=${1:-onosproject}
BASE_BRANCH=${BASE_BRANCH:-master}
VERSIONFILE=${VERSIONFILE:-VERSION}
export VERSIONFILE

# Set up the git environment to allow making commits
repo="${PWD##*/}".git
git remote add upstream https://github.com/${project}/${repo}
git remote set-url origin git@github.com:${project}/${repo}
git remote set-url --push upstream git@github.com:${project}/${repo}

export SEMVER_STRICT=1
export DRY_RUN=0

# Read in the desired version
export VERSION=$(< ./$VERSIONFILE)
vers=(${VERSION//./ })

# go likes 'v' to lead off a version string
export VERSION=v${VERSION}

# Travis leaves you in a detatched HEAD, return to base
git checkout ${BASE_BRANCH}

if ../build-tools/tag-collision-reject; then
  # Do a release build

  # Log in to Docker
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

  # The go build can pollute the tree
  git checkout .
  git clean -fx

  # publish artifacts
  make publish

  # Update the VERSION file to the next dev version
  new_version=${vers[0]}.${vers[1]}.`expr ${vers[2]} + 1`-dev
  echo ${new_version} >./VERSION

  # commit the new VERSION
  git add .
  git commit --author "ONOS CI <onos-builder@opennetworking.org>" -m "Bumping to new development version ${new_version}"
  git push origin ${BASE_BRANCH}
fi

