#!/bin/bash
# Copyright 2020-present Open Networking Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Simple tool to enable or disable push to upstream repo.

case "${1:-off}" in
"on")
  url=$(git remote -v | grep upstream | cut -f2 | grep https | cut -d\  -f1 | sed 's|https://github.com/|git@github.com:|')
  [ -n "$url" ] && git remote set-url --push upstream $url;;
"off")
  git remote set-url --push upstream no_push;;
default)
  echo "usage: $(basename $0) [on|off]" >&2 && exit 1;;
esac

