#!/bin/bash
# Copyright 2020-present Open Networking Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e -u -o pipefail

WEBSITE_USER=$1
WEBSITE_PASSWORD=$2
UPLOAD_USER=$3

declare -a charts=(
  "sd-ran/sd-ran-1.1.4-rev5.tgz"
  "onos-e2sub/onos-e2sub-1.0.3.tgz"
  "onos-e2t/onos-e2t-1.0.24.tgz"
  "ran-simulator/ran-simulator-1.0.49.tgz"
  "onos-kpimon/onos-kpimon-0.6.6.tgz"
  "onos-pci/onos-pci-0.6.6.tgz"
)

source_base_url="https://sdrancharts.onosproject.org/onos-helm-charts/"

rm -rf staging
mkdir -p staging/onos-helm-charts
cd staging

for chart in "${charts[@]}" ; do
  curl -u ${WEBSITE_USER}:${WEBSITE_PASSWORD} -L --silent --create-dirs -o onos-helm-charts/$chart $source_base_url/$chart
done

helm repo index onos-helm-charts/ --url https://publicsdrancharts.onosproject.org/onos-helm-charts

cd onos-helm-charts
/Users/ray/go/src/github.com/onosproject/build-tools/build/_output/index2md -file index >index.html
/Users/ray/go/src/github.com/onosproject/build-tools/build/_output/index2md -file index -html >README.md

cd ..
mv onos-helm-charts/index.yaml onos-helm-charts/index.html onos-helm-charts/README.md .
chmod -R a+r .
chmod +x onos-helm-charts/*

cd ..
rsync -rvzh staging/ $UPLOAD_USER@static.opennetworking.org:/srv/sites/publicsdrancharts.onosproject.org/
