#!/bin/bash
# Copyright 2020-present Open Networking Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e -u -o pipefail

declare -a components=(
  "sdran-helm-charts" "sd-ran-1.1.4-rev4"
  "onos-e2-sm" "servicemodels/e2sm_kpm/v0.7.34"
  "onos-e2-sm" "servicemodels/e2sm_kpm_v2/v0.7.34"
  "onos-e2-sm" "servicemodels/e2sm_rc_pre/v0.7.34"
  "onos-e2-sm" "servicemodels/e2sm_mho/v0.7.34"
  "onos-e2-sm" "servicemodels/e2sm_ni/v0.7.34"
  "onos-e2sub" "v0.7.3"
  "onos-e2t" "v0.7.19"
  "ran-simulator" "v0.7.32"
  "onos-kpimon" "v0.1.9"
  "onos-pci" "v0.1.4"
)

length=${#components[@]}
length=$((length - 1))

GIT_USER=$1
GIT_TOKEN=$2

rm -rf sdran-upload
mkdir sdran-upload
cd sdran-upload

for i in $(seq 0 2 $length); do
  component=${components[$i]}
  version=${components[$i+1]}
  if [ ! -d "$component" ]
  then
    git clone git@github.com:onosproject/$component.git
    cd $component
    git checkout -b rel-1.1.1 $version

    curl -X POST -u$GIT_USER:$GIT_TOKEN https://api.github.com/orgs/sdran/repos -d "{\"name\":\"$component\",\"private\":\"true\"}"

    /Users/ray/go/src/github.com/onosproject/build-tools/dev/release-open-source/fix-sdran-opensource

    git add .
    git commit -m "Updates for open source release"
    git push https://github.com/sdran/$component.git

    /Users/ray/go/src/github.com/onosproject/build-tools/dev/release-open-source/remove-proprietary-sdran-opensource

    cd ..
  fi

  cd $component
  git tag -d $version || true
  git tag $version
  git push https://github.com/sdran/$component.git $version || true
  cd ..

done