#!/bin/bash
# Copyright 2020-present Open Networking Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e -u -o pipefail

GIT_TOKEN=$1

declare -a repos=(
  "ran-simulator"
  "onos-e2sub"
  "onos-e2t"
  "onos-e2-sm"
  "onos-pci"
  "onos-kpimon"
  "sdran-helm-charts"
)


for repo in "${repos[@]}" ; do
  curl -X DELETE -H "Authorization: token $GIT_TOKEN" https://api.github.com/repos/sdran/$repo
done
