#!/bin/bash
# Copyright 2020-present Open Networking Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


set -e -u -o pipefail

declare -a asn1_files=(
  "servicemodels/e2sm_kpm/v1beta1/e2sm-kpm-v01.00.asn1"
  "servicemodels/e2sm_kpm_v2/v2/e2sm_kpm_v2.0.3-changed.asn"
  "servicemodels/e2sm_kpm_v2/v2/e2sm_kpm_v2.0.3-rm.asn.original"
  "servicemodels/e2sm_kpm_v2_go/v2/e2sm_kpm_v2.0.3-radisys.asn"
  "api/e2ap/v1beta2/e2ap-v01.01.00.asn1"
  "api/e2ap/v2beta1/e2ap_v2.0.1_Feb3_21.asn"
)

current_repo=${PWD##*/}

cd ..
git clone --mirror git@github.com:sdran/$current_repo.git

for file in "${asn1_files[@]}"
do
    #see https://rtyley.github.io/bfg-repo-cleaner/
    java -jar ~/Downloads/bfg-1.14.0.jar --delete-files `basename $file` $current_repo.git || true

    cd $current_repo.git
    git reflog expire --expire=now --all && git gc --prune=now --aggressive
    git push
    cd ..
done

